on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: yarn, yarn test, yarn coveralls
      run: |
        export COVERALLS_REPO_TOKEN=hcRtRMzIvnvMU3VXiH0WQMOzcrpou2QEg
        yarn
        yarn test
        yarn coveralls

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
